#ifndef COLOR_IMPLICIT_MODIFIERS_GLSL
#define COLOR_IMPLICIT_MODIFIERS_GLSL

#include "../implicit/types.glsl"
#include "types.glsl"

// modifiers.glsl
// Generated by GLSL Reorganizer
// Functions: 1 functions

// From: mixing.glsl:33
ColorImplicit TriangleWaveEvenPositive(ColorImplicit param, float period) {
    Implicit base = TriangleWaveEvenPositive(Implicit(param.Distance, param.Gradient), period);
    return ColorImplicit(base.Distance, base.Gradient, param.Color);
}

#endif // COLOR_IMPLICIT_MODIFIERS_GLSL
